apiVersion: apps/v1
kind: Deployment
metadata:
  name: mikroserwis-a-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mikroserwis-a
  template:
    metadata:
      labels:
        app: mikroserwis-a
    spec:
      containers:
        - name: mikroserwis-a
          image: kacperholowaty/mikroserwis_a:latest
          ports:
            - containerPort: 3000
